use QLHH

--TÌNH HUỐNG 1 T1 TANG GIA SANPHAM, SAU ĐÓ DELAY 10S SAU ĐÓ GẶP TRỤC TRẶC ROLLBACK, SONG SONG VỚI ĐÓ T2 TRUY CAP ĐỌC DỮ LIỆU RÁC
--TRANSACTION 1
CREATE PROCEDURE TANGGIASANPHAM @MASP CHAR(10)
AS
	BEGIN TRAN
	UPDATE SANPHAM SET GIA = GIA + 5000
	WHERE MASP = @MASP
	WaitFor Delay '00:00:10'
COMMIT

--DROP PROCEDURE TANGGIASANPHAM

--TRANSACTION 2
CREATE PROCEDURE THONGKESANPHAM 
AS
	BEGIN TRAN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT * FROM SANPHAM
COMMIT

--DROP PROCEDURE THONGKESANPHAM

--TÌNH HUỐNG 2 T1 NÂNG HẠNG CHO TAIKHOAN MÀ LOAITAIKHOAN LÀ STAFF, SAU ĐÓ DELAY 10S RỒI ROLLBACK, SONG SONG VỚI ĐÓ T2 TRUY CAP ĐỌC DỮ LIỆU CHƯA ROLLBACK => DỮ LIỆU RÁC
--TRANSACTION 1
CREATE PROCEDURE NANGHANG @LOAITAIKHOAN NVARCHAR(13)
AS 
	BEGIN TRAN
	SET TRANSACTION ISOLATION LEVEL Repeatable Read
	UPDATE TAIKHOAN SET LOAITAIKHOAN = 'manager'
	WHERE LOAITAIKHOAN = @LOAITAIKHOAN
	WaitFor Delay '00:00:10'
COMMIT

--DROP PROCEDURE NANGHANG

--TRANSACTION 2
CREATE PROCEDURE THONGKETAIKHOAN
AS
	BEGIN TRAN
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	SELECT * FROM TAIKHOAN
COMMIT

--DROP PROCEDURE THONGKETAIKHOAN