USE QLHH

--TÌNH HUỐNG 1 T1 TANG GIA SANPHAM, SAU ĐÓ DELAY 10S SAU ĐÓ GẶP TRỤC TRẶC ROLLBACK, SONG SONG VỚI ĐÓ T2 TRUY CAP ĐỌC DỮ LIỆU RÁC
--TRANSACTION 2
EXEC THONGKESANPHAM 

--TÌNH HUỐNG 2 T1 NÂNG HẠNG CHO TAIKHOAN MÀ LOAITAIKHOAN LÀ STAFF, SAU ĐÓ DELAY 10S RỒI COMMIT, SONG SONG VỚI ĐÓ T2 TRUY CAP ĐỌC DỮ LIỆU UNCOMMITED => DỮ LIỆU RÁC
--TRANSACTION 2
EXEC THONGKETAIKHOAN
